### ISSUE TITLE
Setup pre-commit

### ISSUE THREAD

**Issue by vivekashok1221** [idkbrowby/gamingrealm-backend#1]
Setup pre-commit hooks with [pre-commit](https://pre-commit.com/).

**Comment by anand2312** [comment]
Odd, github didn't close this when the PR was closed (possible because you should've written `Closes #1` instead of `Closes issue #1` in the PR description, so the issue didn't get [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
